%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/antoine/EPFL/Project_II/byextopopt/src/check_config.out
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/08 14:06:19

%% Initialize variables.
filename = '/home/antoine/EPFL/Project_II/byextopopt/src/check_config.out';
delimiter = ',';
startRow = 6;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
x = dataArray{:, 1};
y = dataArray{:, 2};
fx = dataArray{:, 3};
fy = dataArray{:, 4};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% plot
r = max(x)/2;
xc = max(x)/2;
yc = max(y)/2;
th = 0:pi/50:2*pi;
xunit = r * cos(th) + xc;
yunit = r * sin(th) + yc;
figure
grid on
plot(x,y,'x')
hold on
grid on
quiver(x,y,fx,fy)
plot(xunit,yunit,'--r')
title("Configuration of fixed nodes and force for wheel problem")
legend("fixed nodes","forces")
xlim([0 max(x)])
ylim([0 max(y)])